public enum Skin
{
	SKIN_ROB = 0,
	SKIN_NOOB = 1,
	SKIN_NINJA = 2,
	SKIN_SPIDA = 3,
	SKIN_BADMON = 4,
	SKIN_CAPTAIN = 5,
	SKIN_IRON = 6,
	SKIN_DEAD_PULL = 7,
	SKIN_GOKU = 8,
	SKIN_JASON = 9,
	SKIN_SLENDERMAN = 10,
	SKIN_VENOM = 11,
	SKIN_MARIO = 12,
	SKIN_MABU = 13,
	SKIN_BIG6 = 14
}
